version: '3.7'

networks:
    whook:

services:
    app:
        build: 
            context: .
            dockerfile: Dockerfile
        image: qlikgear/qmicloud-webhook:latest
        container_name: qmicloud-webhook
        restart: on-failure
        environment:
            - TRIGGER_STATUS=Stopped
            - QMICLOUD_API_URL=https://qmicloud.qliktech.com/api/v1/divvy/updates
            - QMICLOUD_KEY=xxx
        ports:
            - "8080:80"
        networks:
            - whook
        
    dozzle:
        image: amir20/dozzle:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 8888:8080
        #environment: 
        #    DOZZLE_BASE: "/dozzle"
        networks:
            - whook