version: '3.7'

networks:
    whook:

services:
    webhook_stop:
        image: qlikgear/qmicloud-webhook:latest
        deploy:
            replicas: 1
            restart_policy:
              condition: on-failure
        environment:
            - TRIGGER_STATUS=Stopped
            - QMICLOUD_API_URL=https://qmicloud.qliktech.com/api/v1/divvy/updates
            - QMICLOUD_KEY=4580d77e74993814484ccc1ba016b6e99da88a6b7d8148985a54c88b0a10b4ac668c293555c4248872a67f0e7404d4b1cf6c2eb8994ae99f430f3c5e17766a74
        ports:
            - 5000:5000
        networks:
            - whook
    webhook_start:
        image: qlikgear/qmicloud-webhook:latest
        deploy:
            replicas: 1
            restart_policy:
              condition: on-failure
        environment:
            - TRIGGER_STATUS=Running
            - QMICLOUD_API_URL=https://qmicloud.qliktech.com/api/v1/divvy/updates
            - QMICLOUD_KEY=4580d77e74993814484ccc1ba016b6e99da88a6b7d8148985a54c88b0a10b4ac668c293555c4248872a67f0e7404d4b1cf6c2eb8994ae99f430f3c5e17766a74
        ports:
            - 6000:5000
        networks:
            - whook
