version: '3.7'

networks:
    whook:

services:
    webhook_stop:
        image: qlikgear/qmicloud-webhook:latest
        deploy:
            replicas: 1
            restart_policy:
              condition: on-failure
        environment:
            - TRIGGER_STATUS=Stopped
            - QMICLOUD_API_URL=http://app:3000/api/v1/divvy/updates
            - QMICLOUD_KEY=xxx
        ports:
            - 5001:5050
        networks:
            - qmi-net
    webhook_start:
        image: qlikgear/qmicloud-webhook:latest
        deploy:
            replicas: 1
            restart_policy:
              condition: on-failure
        environment:
            - TRIGGER_STATUS=Running
            - QMICLOUD_API_URL=http://app:3000/api/v1/divvy/updates
            - QMICLOUD_KEY=xxx
        ports:
            - 5000:5050
        networks:
            - qmi-net
